hardware-software-interface/registers-and-memory-addressing: Add reading, guides and tasks
cs-pub-ro/hardware-software-interface pull request #19
Opened 2024-03-31 18:20 UTC by andreistan26

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

Introducing lab 6 - `Registers and memory addressing`.

- Add `chapters/hardware-software-interface/memory-addressing/`
- Add `chapters/hardware-software-interface/registers/`
- Update `config.yaml`

2024-04-02 05:01 UTC, teodutu requested changes
Nice work overall! I made some inline suggestions, most of which should be applied to all files of that type.

2024-04-02 05:01 UTC, teodutu commented on chapters/hardware-software-interface/registers/reading/README.md
> +>![Memory Sections](../media/sections.svg)
```suggestion
> **NOTE**: DB, DW, DD are directives used to specify the size of the portion:
> Directive | Role               | Size
> --------- | ------------------ | ----
> `db`      | Define Byte        | 1 bytes (8 bits)
> `dw`      | Define Word        | 2 bytes (16 bits)
> `dd`      | Define Double Word | 4 bytes (32 bits)
>
> **NOTE**: There are multiple types of memory regions as can be seen in the image below:
>
> ![Memory Sections](../media/sections.svg)
```

2024-04-02 05:01 UTC, teodutu commented
I'll go over the guides sometime later today.

2024-04-02 05:19 UTC, teodutu commented on chapters/hardware-software-interface/memory-addressing/guides/addressing-arrays/support/addressing-arrays.asm
Being a guide, it may be a good idea to add some comments explaining what it does in more detail. For example, what each register is used for and what each block of instructions does.

2024-04-02 17:14 UTC, teodutu requested changes
You still need to do the following:
- change the names of source code files to `file_name.asm` (as well as their mentions in Markdown files and makefiles
- Recreate the `.svg` files on draw.io so they're actually editable.

2024-04-02 17:33 UTC, andreistan26 commented on chapters/hardware-software-interface/memory-addressing/drills/tasks/sum-array/solution/Makefile
Sure thing

2024-04-02 17:35 UTC, andreistan26 commented on chapters/hardware-software-interface/memory-addressing/guides/addressing-arrays/support/addressing-arrays.asm
Sure, will go again through the `guides/*/{README.md,support/}`  and refactor them.

2024-04-03 10:22 UTC, teodutu approved these changes
I think it's OK now. Let's wait for @denismarian1604 and @alexandru-braslasu to review as well.

2024-04-03 10:55 UTC, denismarian1604 commented on chapters/hardware-software-interface/registers/drills/tasks/mul/README.md
> +Update the marked area with `TODO` in the file `multiply.asm` to allow multiplication of `word` and `dword` numbers, namely `num1_dw` with `num2_dw`, and `num1_dd` with `num2_dd`.
```suggestion
Update the area marked with `TODO` in the file `multiply.asm` to allow multiplication of `word` and `dword` numbers, namely `num1_dw` with `num2_dw`, and `num1_dd` with `num2_dd`.
```

2024-04-03 10:56 UTC, denismarian1604 commented on chapters/hardware-software-interface/memory-addressing/drills/tasks/vec-count-if/README.md
> +Your program should display the number of even and odd numbers from an array.
```suggestion
Your program should display the number of even and odd values from an array.
```

2024-04-03 10:56 UTC, denismarian1604 commented on chapters/hardware-software-interface/memory-addressing/drills/tasks/vec-count-if/README.md
> +Your program should display the number of positive and negative numbers from the array.
```suggestion
Your program should display the number of positive and negative values from the array.
```

2024-04-04 04:48 UTC, denismarian1604 approved these changes
Nice work 👍

2024-04-04 08:20 UTC, merged