stack/functions: Add functions lab.
cs-pub-ro/hardware-software-interface pull request #21
Opened 2024-04-21 17:50 UTC by razvang0307

Added functions lab based off old lab material.
Ignored throwback exercise 0.

# Prerequisite Checklist

- [ ] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [X] Tested your changes against relevant architectures and platforms;
- [X] Updated relevant documentation (if needed).

## Description of changes

Added the lab materials for function calls in assembly.

2024-04-22 20:36 UTC, teodutu requested changes
Things are looking nice so far. I highlighted what needs to be done in my inline comments and besides those, you should also do the following globally:

- Add a `.gitignore` file to all `support/` and `solution/` folders. This file should only exclude the executable file and **not** the object file (`.o`) because object files are already excluded by the `.gitignore` in the root of the repo.
- Take a look at the linter errors and fix them [1]. To fix the Spellcheck errors you'll also have to add the false positives (correct words flagged as incorrect because they're missing from the action's wordlist) to the wordlists here. Create a PR in which you add the new words to the corresponding files here [2]. After changing a file, run `sort -u -f <file_name.txt> <file_name.txt>` to remove duplicates. Remember to add the conjugations and declinations of each word as well as the word itself.
- Squash your commits into a single one as described here [3]. For further modifications, use `git commit --amend --no-edit` to add them to the existing commit.

[1] https://github.com/cs-pub-ro/hardware-software-interface/pull/21/checks
[2] https://github.com/open-education-hub/actions/tree/main/spellcheck/config
[3] https://www.freecodecamp.org/news/git-squash-commits/

2024-04-22 20:36 UTC, teodutu commented on chapters/stack/functions/media/stack.svg
Increase the font of all text to 20 instead of 12.

2024-04-22 20:36 UTC, teodutu commented on chapters/stack/functions/reading/README.md
> +   mov ecx, dword [ebp+16]  ; third argument in ecx
```suggestion
   mov eax, [ebp + 8]   ; first argument in eax
   mov ebx, [ebp + 12]  ; second argument in ebx
   mov ecx, [ebp + 16]  ; third argument in ecx
```

2024-04-24 17:14 UTC, george-cosma requested changes
Yhea, most of it is fine. Good work! I left some comments though that I'd like your input on. Feel free to disagree.

2024-04-24 17:14 UTC, george-cosma commented on chapters/stack/functions/reading/README.md
> +5. A function uses the same hardware registers; therefore, when exiting the function, the values of the registers are no longer the same. To avoid this situation, some/all registers can be saved on t
I would encourage to mention `pusha` and `popa` (and their downsides -- fucks up the eax register).

2024-04-24 17:14 UTC, george-cosma commented on chapters/stack/functions/reading/README.md
> +> For us, the registers `eax`, `ecx`, `edx` are considered **clobbered** (or volatile), and the callee can do whatever it wants to them. On the other hand, the callee has to ensure that `ebx` exits t
I suggest moving this information (what registers we can ovewrite and not) to main-body contents, maybe beneath `5.`. It's important info. Though this is more of an aesthetics change - so I don't feel strongly about it.

2024-04-24 17:14 UTC, george-cosma commented on chapters/stack/functions/guides/hello_world/support/hello_world.asm
> +extern puts
```suggestion
extern puts ; we need to mark "puts()" as an external function, not one found in this file
```

I'd add even more details than what I sugested. Make sure that the students understan what `extern` is. Perhaps even add a section about it in the main content?

2024-04-24 17:21 UTC, george-cosma commented
Oh, and one more comment: Do we need to put the content under `Lab9/Functions/{Reading/Guides/...}`. Shouldn't it be just `Lab9/{Reading/Guides/...}`, skip on the unnecessary sub-heading?

2024-04-24 21:25 UTC, savacezarmarian14 commented on chapters/stack/functions/drills/tasks/print_rev_string/solution/print_reverse_string.asm
> +section .data
Maybe add some explanation comments if this is the solution. I think students should read the comments rather than copy the code

2024-04-24 21:27 UTC, savacezarmarian14 commented on chapters/stack/functions/drills/tasks/string_print/solution/print_string.asm
> +    add esp, 4
Students will not understand why this `add esp, 4` is needed when the call returns

2024-04-24 21:27 UTC, savacezarmarian14 commented on chapters/stack/functions/drills/tasks/string_print/support/print_string.asm
> +    ret
I strongly recommand a new line at the end of file. See [1]
[1] https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3

2024-04-24 21:30 UTC, savacezarmarian14 commented on chapters/stack/functions/drills/tasks/string_print_len/support/print_string_length.asm
> +    mov bl, byte [eax]
Please explain to me why we erase the "known length" operations?

2024-04-24 21:32 UTC, savacezarmarian14 requested changes
Please check my comments. Also keep in mind that i didn't comment at all files that should have changes. IT LOOKS GOOD FROM MY POINT OF VIEW.

2024-05-22 08:05 UTC, teodutu commented
ping @razvang0307

2025-01-07 19:47 UTC, merged