chapters/memory-security/ctf: Add CTF lab
cs-pub-ro/hardware-software-interface pull request #25
Opened 2024-08-29 02:48 UTC by valudimi

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/open-education-hub/ccas-internal/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes

This commit adds the adapted material, including references and sentence rephrasing for enhanced readability, as well as solution writeups.

2024-08-29 10:28 UTC, teodutu requested changes
Things are looking well for the most part. Below are some things that are missing, besides my inline comments. 

- Some exercises are missing their source code, such as `feeling-chained`. You can find them here [1]. Add them to the `solution/` folders so we don't lose them and have them all in one place.
- Add the makefiles to all exercises because some of them define necessary compiler flags such as `-fno-stack-protector`
- Provide the paths to all files that students must use. For example write `task-name/support/binary` instead of just `binary`.
- Modify all flags to start with `HSI_` instead of `iocla_` and then use `obfuscate.c` [2] to embed it in the source code. I'm not sure whether to add the contents of [2] to every task's `solution/` folder or not. Let's not do this for now since this tool is also used for CTFs which need to be private because they are contests. We can always add it later if needed.

[1] https://github.com/systems-cs-pub-ro/iocla-internal/tree/master/laboratoare/content/ctf/sol
[2] https://github.com/systems-cs-pub-ro/iocla-internal/tree/master/comunitate/ctf/obfuscator

2024-08-29 10:28 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/indirect-business/solution/README.md
> +`python -c 'import sys; sys.stdout.write("A"*10 + "Bye")' | ./buff-ovf`
```suggestion
`python -c 'import sys; sys.stdout.buffer.write(b"A"*10 + b"Bye")' | ./buff-ovf`
```

This is a bit messy, but we mostly give raw bytes as payloads especially when we provide addresses. For this we need `sys.stdout.buffer.write()`, not just `sys.stdout.write()`. Since we're targeting 1st year students, who don't know about OS internals yet, let's use the more generic call each time.

In addition, use block code for longer commands. It makes them stand out better. I can't make an inline suggestion with this because GitHub is retarded and its suggestion API uses block code itself, thus messing up the suggestion itself :upside_down_face:

2024-09-05 02:55 UTC, teodutu commented
Don't forget to add the sources for the binaries so we have them all in one place.

2024-09-14 04:55 UTC, teodutu requested changes
Things are looking considerably better now and the solutions are clear and straightforward. GG! My inline comments now focus on smaller details, but most of them apply to all tasks.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/feeling-chained/solution/README.md
> +```
Move this command to a script file. And the same for all `solution/README.md`s. Each solution should have a script file that obtains the flag except for when the solution requires using GDB, linking a file, or anything that cannot be scripted.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/feeling-chained/support/buff-ovf3
Make all executable files executable: `chmod +x`.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/hidden-in-plain-sight-2/solution/README.md
> +In a nature similar to that of the previous exercise, we take a close look at the `objdump` disassembly output of the binary using the `objdump -D -M intel link2` command, specifically focusing on th
Replace "previous exercise" with `[hidden-in-plain-sight-1](link/to/hidden-in-plain-sight-1)`.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/indirect-business/solution/README.md
> +python -c 'import sys; sys.stdout.buffer.write(b"A"*10 + b"Bye")' | ./buff-ovf
```suggestion
python3 -c 'import sys; sys.stdout.buffer.write(b"A"*10 + b"Bye")' | ./buff-ovf
```

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/README.md
> +By using commands like `ropsearch "pop rsi"` and `ropsearch "pop rdi"` in `GDB peda`, you will find gadgets `pop rsi; pop r15; ret` and `pop rdi; ret`.
```suggestion
By using commands like `rop --grep "pop rsi"` and `rop --grep "pop rdi"` in `pwndbg`, you will find gadgets `pop rsi; pop r15; ret` and `pop rdi; ret`.
```
We don't use peda anymore.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/README.md
> +We first need to overwrite the return address with the address of the first gadget, followed by 2 8-bytes values (rsi and r15, which is not relevant);
```suggestion
We first need to overwrite the return address with the address of the first gadget, followed by 2 8-byte values (`rsi` and `r15`, which are not relevant);
```

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/README.md
> +The binary is a 64-bits ELF, therefore the parameters are no longer taken from the stack - they are taken from registers esi and edi;
```suggestion
The binary is a 64-bits ELF, therefore the parameters are no longer taken from the stack - they are taken from registers `edi` and `esi` in this order;
```

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/README.md
Add an image to showcase the stack after sending the payload: which values point to gadgets and which numbers are popped into register. Use https://app.diagrams.net/ to create and save it in `.SVG` format.

2024-09-14 04:55 UTC, teodutu commented on chapters/memory-security/ctf/reading/README.md
> +## Return Oriented Programming
You need to expand on what gadgets are and what ROPs do. I created the image below for a ROP demo I made the other day. You can use it as a start. Explain what happens step by step, which value on the stack goes where and it should be clearer.

![rop-anatomy](https://github.com/user-attachments/assets/a9540377-0ce5-4b36-98f3-9add6ce1f8da)

2024-10-04 12:32 UTC, teodutu requested changes
I only made suggestions that should be applied to all `solve.sh`s. Don't worry about the line length. Don't worry about the line length.

2024-10-04 12:32 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/README.md
On second thought, this might not be needed.

2024-10-04 12:32 UTC, teodutu commented on chapters/memory-security/ctf/drills/tasks/rop/solution/solve.sh
Make this file executable

2024-10-04 12:32 UTC, teodutu commented on chapters/memory-security/ctf/reading/README.md
> +## Return Oriented Programming
Bump on this though. This would be of great use. You already have the image above, just add some text to walk students through it.

2024-10-06 16:05 UTC, NickZaharia308 requested changes
Looks great! :+1:
Address the changes made by Teo Dutu and everything should be fine.

2024-12-30 17:09 UTC, teodutu approved these changes

2024-12-30 17:09 UTC, merged